kind: Deployment
apiVersion: apps/v1
metadata:
  name: support-desk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-desk
  template:
    metadata:
      labels:
        app: support-desk
    spec:
      containers:
        - name: support-desk
          image: support-desk:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: support-desk
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: support-desk